const mongoose = require('mongoose');
const FacilitiSchema = mongoose.Schema({
  hotelObj: { type: Object },
  COAlarmSensor: { type: Boolean, default: false },
  Dryer: { type: Boolean, default: false },
  Fireplace: { type: Boolean, default: false },
  FirstAidKit: { type: Boolean, default: false },
  Hairdryer: { type: Boolean, default: false },
  Kitchen: { type: Boolean, default: false },
  Shampoo: { type: Boolean, default: false },
  SmokeDetector: { type: Boolean, default: false },
  Smoking: { type: Boolean, default: false },
  TowelsOfAllKinds: { type: Boolean, default: false },
  airConditional: { type: Boolean, default: false },
  beddingSet: { type: Boolean, default: false },
  cableTelevision: { type: Boolean, default: false },
  coffee: { type: Boolean, default: false },
  doorStaff: { type: Boolean, default: false },
  elevatorInHotel: { type: Boolean, default: false },
  fireExtinguisher: { type: Boolean, default: false },
  freeBreakfast: { type: Boolean, default: false },
  freeInternet: { type: Boolean, default: false },
  freeParking: { type: Boolean, default: false },
  freeWifi: { type: Boolean, default: false },
  gymRoom: { type: Boolean, default: false },
  heaters: { type: Boolean, default: false },
  hotTub: { type: Boolean, default: false },
  indooPool: { type: Boolean, default: false },
  internetCharge: { type: Boolean, default: false },
  ironingMachine: { type: Boolean, default: false },
  outdoorSwimmingPool: { type: Boolean, default: false },
  petsAllowed: { type: Boolean, default: false },
  privatePool: { type: Boolean, default: false },
  smartKey: { type: Boolean, default: false },
  tea: { type: Boolean, default: false },
  teaMaker: { type: Boolean, default: false },
  television: { type: Boolean, default: false },
  washingMachine: { type: Boolean, default: false },
  wheelchairAccessible: { type: Boolean, default: false },
  wifiCharge: { type: Boolean, default: false },
  wirelessBell: { type: Boolean, default: false },
  workspace: { type: Boolean, default: false }
}, {
  timestamps: true
});
module.exports = mongoose.model('Facilities', FacilitiSchema);
